### ISSUE TITLE
Unable to edit

### ISSUE THREAD

**Issue by jeff-bronks** [Theophilix/EventTableEdit#3]
Thank you for publishing this extension. It would be perfect for my needs if I could get it to work!

I installed ETE on a J4 (4.2.0) site. I can create an empty table and see it on the site. I can also see and use the admin functions such as 'Administer table' and 'Export CSV', but I cannot edit anything as a user. Clicking on a cell does nothing. Clicking the green + symbol to add a row does nothing. 

Some things I have tried:
* Setting all access control fields to 'Allowed'
* Moving the table from a submenu to a root menu
* Enabling and disabling SEF URLs
* Logging in to the site as a Registered User/logging out

Are you able to offer any other suggestions please? The console output looks like this:

![image](https://user-images.githubusercontent.com/112024035/187070662-7b71d8e7-23ba-4ce8-bf3a-12caaeabb058.png)

**Comment by jeff-bronks** [comment]
I got the edit function working. The clue was the 'unexpected token' error in the console. It means that you are not allowed to have a space in the table name (which becomes a hyphen in the table name alias). Hyphens are bad.

I changed the table name to a single word without spaces and now the edit function works.

**Comment by Theophilix** [comment]
Fixed in 1.02 version.
